---
- name: Ensure ~/.gitconfig copied from master.gitconfig
  hosts: localhost
  tasks:
  - copy:
      src: "../adhoc/master.gitconfig"
      dest: "~/.gitconfig"
      
- name: Ensure bat jq and vagrant are installed
  gather_facts: false
  hosts: localhost
  tasks:
  - apt:
      name:
        - bat
        - jq
        - vagrant
      state: present
    become: true
    